# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: AIBankApp-CI-CD

on:
  push:
    branches: [ "main" ]

  pull_request:
    branches: [ "main" ]

jobs:

  build-maven:
    runs-on: ubuntu-latest

    steps:
    # -------------------------------
    #  Checkout Source Code
    # -------------------------------
    - name: Checkout Repository
      uses: actions/checkout@v4

    # -------------------------------
    # Setup Java
    # -------------------------------

    - name: Build with Maven
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    # -------------------------------
    #  Cache Maven Packages
    # -------------------------------
    - name: Cache Maven Dependencies
      uses: actions/cache@v4
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    # -------------------------------
    # Build Application
    # -------------------------------
    - name: Build with Maven
      run: mvn clean package -DskipTests

  Image-build-Scan-Push:      
    runs-on: ubuntu-latest

    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    steps:
    # -------------------------------
    #  Checkout Source Code
    # -------------------------------
    - name: Checkout Repository
      uses: actions/checkout@v4

    # -------------------------------
    # Trivy File System Scan
    # -------------------------------
    - name: Install Trivy
      run: |
        curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sudo sh -s -- -b /usr/local/bin
      
    # -------------------------------
    # Docker Login
    # -------------------------------
    - name: DockerHub Login
      run: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

    # -------------------------------
    # Build Docker Image
    # -------------------------------
    - name: Build Docker Image
      run: |
        docker build -t aibankapp .
        docker tag aibankapp:latest $DOCKER_USERNAME/aibankapp:latest
    # -------------------------------
    # Trivy Docker Image Scan
    # -------------------------------
    - name: Trivy Image Scan
      run: |
        trivy image --severity HIGH,CRITICAL --format table -o trivy-report.txt $DOCKER_USERNAME/aibankapp:latest

    # -------------------------------
    # Push Image to DockerHub
    # -------------------------------
    - name: Push Docker Image
      run: |
        docker push $DOCKER_USERNAME/aibankapp:latest   
