name: Destroy EKS Cluster

on:
  workflow_dispatch:

env:
  AWS_REGION: ap-south-1
  CLUSTER_NAME: bankapp_aws-cluster

jobs:
  destroy:
    runs-on: ubuntu-latest

    steps:

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Install eksctl
      run: |
        curl -sLO https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_Linux_amd64.tar.gz
        tar -xzf eksctl_Linux_amd64.tar.gz
        sudo mv eksctl /usr/local/bin/

    - name: Delete Cluster
      run: eksctl delete cluster --name $CLUSTER_NAME --region $AWS_REGION